[[rules]]
name = "星野源のオールナイトニッポン"
station_id = "LFR"
weekday = "Wed"
start = "01:00"
duration = "2h"

[[rules]]
name = "オードリーのオールナイトニッポン"
station_id = "LFR"
weekday = "Sun"
start = "01:00"
duration = "2h"


[[rules]]
name = "ナインティナインののオールナイトニッポン"
station_id = "LFR"
weekday = "Fri"
start = "01:00"
duration = "2h"
