out_dir_path = "/opt/radiko-archiver"
rules_path = "/etc/radiko-archiver/rules.toml"

[radiko]
offset_time = "6h"
planner_interval = "10m"
fetch_timeout = "3m"

[feed]
enabled = false
port = 8080
base_url = "http://localhost:8080"

[dropbox]
enabled = true
